# разработчик плагина Soldi_n .jar
# PlayerSoldInFake – конфигурация
enabled: true

# Диапазон количества фейковых игроков одновременно в табе
min-fake-online: 4
max-fake-online: 15

# Как часто менеджер проверяет план действий (секунды)
tick-interval-seconds: 20

# Сколько в среднем "сессия" длится (минуты) – фейковый игрок после этого прерывает присутствие
session-minutes-min: 120
session-minutes-max: 180

# Вероятность, что фейковый игрок напишет сообщение при одном тике менеджера (0.0..1.0)
chat-random-chance: 0.03

# Отображать join/quit сообщения от имени фейковых игроков
fake-join-quit-messages: true

# Форматы сообщений
formats:
  join: "&e%name% &7зашёл на сервер."
  quit: "&e%name% &7вышел с сервера."
  chat: "&7%name%: &f%message%"

# Предзаданные фразы (рандомно выбираются)
chat-messages:
  - "Всем привет!"
  - "Кто пойдёт в шахту?"
  - "Есть у кого еда?"
  - "GG"
  - "Продам алмазы"
  - "Скоро вайп?"
  - "Как дела?"

# База имён для генерации
names:
  - Alexey
  - Artem
  - Ivan
  - Vlad
  - Marina
  - Katya
  - Nickita
  - ProPlayer
  - NoobMaster
  - xXx_Soldi_n_xXx

# Префиксы/суффиксы для генерации случайных ников
name-gen:
  prefixes: ["xX", "The", "Pro", "Mr", "Mrs", "i", "Q"]
  suffixes: ["_YT", "_TV", "HD", "1337", "Pro", "xx", "MC"]

