# Разработчик плагина: Soldi_n

# Минимум игроков в TAB
min-players: 4

# Максимум игроков в TAB
max-players: 15

# Сообщения, которые будут писать фейковые игроки
fake-messages:
  - "Привет всем!"
  - "Кто пойдёт в шахту?"
  - "Эх, опять ночь..."
  - "Сервер топ :)"

# Интервал (в секундах), через который могут заходить/выходить фейковые игроки
join-leave-interval: 120

# Включить ли автоматическое общение фейков
chat-enabled: true
