name: PlayerSoldInFake
main: com.soldin.playersoldinfake.PlayerSoldInFakePlugin
version: 1.0.0
api-version: "1.16"
author: "Soldi_n"
website: "https://example.com"
depend: [ProtocolLib]
commands:
  psif:
    description: PlayerSoldInFake admin commands
    usage: /psif <reload|addrandom|add|remove|removeall> [...]
    permission: playersoldinfake.admin
permissions:
  playersoldinfake.admin:
    default: op
