name: playersoldinfake
main: me.yourname.playersoldinfake.PlayersOldInFake
version: 1.0.0
api-version: '1.16'
authors: [you]
softdepend: [ProtocolLib]
commands:
  playersoldinfake:
    description: Управление фейковыми игроками
    usage: /<command> [reload|add|remove|removeall|addrandom]
    aliases: [psf]
    permission: playersoldinfake.admin
permissions:
  playersoldinfake.admin:
    default: op
